matrix:
  include:
    - language: node_js
      node_js:
        - 11
      before_script:
        - yarn global add redoc-cli
      script:
        - ./ci.sh apis

    - language: python
      python:
        - 3.7
      script:
        - ./ci.sh puml
