matrix:
  include:
    - language: node_js
      node_js:
        - 11
      addons:
        apt:
          packages:
            - jq
      before_script:
        - yarn global add redoc-cli mustache
      script:
        - ./ci.sh apis

    - language: python
      python:
        - 3.7
      script:
        - ./ci.sh puml
